/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package post_gui;

import java.text.NumberFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import transaction.CashPayment;
import transaction.CheckPayment;
import transaction.CreditPayment;
import transaction.Payment;
import transaction.TransactionHeader;

/**
 *
 * @author Travis
 */
public class PaymentPanel extends javax.swing.JPanel {

    double amount;
    double total;
    JFrame mediator;

    /**
     * Creates new form PaymentPanel
     */
    public PaymentPanel() {
        initComponents();
        String[] paymentTypes = {"cash", "credit", "check"};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLable_amount = new javax.swing.JLabel();
        pay_button = new javax.swing.JButton();
        jComboBox_payType = new javax.swing.JComboBox<>();
        jTextField_amount = new javax.swing.JTextField();
        change = new javax.swing.JLabel();
        creditCardNum = new javax.swing.JTextField();

        jLabel9.setText("Payment type");

        jLable_amount.setText("Amount");

        pay_button.setText("Pay");
        pay_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_buttonActionPerformed(evt);
            }
        });

        jComboBox_payType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField_amount.setText("0.00");

        change.setText("change");

        creditCardNum.setText("123456789");
        creditCardNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditCardNumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_payType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pay_button)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(change)
                                .addGap(34, 34, 34))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLable_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jTextField_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(creditCardNum, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creditCardNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLable_amount)
                        .addComponent(jTextField_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jComboBox_payType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(change)
                    .addComponent(pay_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pay_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_buttonActionPerformed

        String selectType = jComboBox_payType.getSelectedItem().toString();
        Payment payment = null;
        String txt = jTextField_amount.getText().trim();
        if (!txt.isEmpty()) {  // generate double value of amount to be paid
            amount = Double.parseDouble(jTextField_amount.getText().trim());
        } else amount = total;
        switch (selectType) {
            case "cash":        
                payment = new CashPayment(total, amount);
                break;
            case "check":
                payment = new CheckPayment(total, amount);
                break;
            case "credit":
                payment = new CreditPayment(total, creditCardNum.getText());
                break;
        }

        
        

        if (post.pay(payment)) {
            change.setText(NumberFormat.getCurrencyInstance().format(payment.getChange()) + "");
            // finish one transaction sets start_newTrans buttons active

        } //invalid credit card
        else {
            if (payment instanceof CashPayment) {
                // warning message
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame,
                        "Sorry, you don't have enough $$$ ...",
                        "error",
                        JOptionPane.WARNING_MESSAGE);
            } else {
                System.out.println("Payment declined.");
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame,
                        "METHOD OF PAYMENT DECLINED",
                        "error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_pay_buttonActionPerformed

    private void creditCardNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditCardNumActionPerformed

    }//GEN-LAST:event_creditCardNumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel change;
    private javax.swing.JTextField creditCardNum;
    private javax.swing.JComboBox<String> jComboBox_payType;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLable_amount;
    private javax.swing.JTextField jTextField_amount;
    private javax.swing.JButton pay_button;
    // End of variables declaration//GEN-END:variables
}
